name: C/C++ CI

on:
  workflow_dispatch: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  take1:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
    - uses: actions/checkout@v3
    - name: suh
      run: |
        wget https://archive.org/download/zelda_ocarina_mq_dbg/zelda_ocarina_mq_dbg.zip/zelda_ocarina_mq_dbg.z64
        mv *.z64 baserom_original.z64
        chmod +x /opt/devkitpro/devkitARM/arm-none-eabi/bin/*
        cp /opt/devkitpro/devkitARM/arm-none-eabi/bin/* tools/ido7.1_compiler/usr/bin/

        cd /opt/devkitpro/devkitARM/bin
        chmod +x *
        cp * /opt/devkitpro/tools/bin
        sudo apt update
        sudo apt full-upgrade -y
        sudo apt install build-essential libpng-dev -y
        
    - name: make
      run: |
        make setup
        make
      
    - uses: actions/upload-artifact@master
      with:
        name: oot
        path: build
