name: C/C++ CI

on:
  workflow_dispatch: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  take1:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
    - uses: actions/checkout@v3
    - name: suh
      run: |
        wget https://archive.org/download/zelda_ocarina_mq_dbg/zelda_ocarina_mq_dbg.zip/zelda_ocarina_mq_dbg.z64
        mv *.z64 baserom_original.z64
        cd /opt/devkitpro/devkitARM/bin
        cp arm-none-eabi-cpp cpp
        cp arm-none-eabi-c++ c++
        cp arm-none-eabi-gcc gcc
        cp arm-none-eabi-g++ g++
        chmod +x *
        cp * /opt/devkitpro/tools/bin
        
    - name: make
      run: |
        export CC=g++
        export CXX=g++
        make setup
        make
      
    - uses: actions/upload-artifact@master
      with:
        name: oot
        path: build
